<?php

namespace Database\Seeders;

use App\Models\SuccessStories;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SuccessStoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $info_ar = '
            <p>
                هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من
                .النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق   
            </p>
            <p>
            إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى
            .مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع  
            </p>
            <p>
            ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص
           بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق     
            </p>
            <p>
            هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتا       
            </p>
        ';

        $info_en = '
            <p>
                This text is an example of a text that can be replaced in the same space. This text was generated from the Arabic text generator, where you can generate such text or many
                Other texts in addition to increasing the number of characters generated by the application
            </p>
            <p>
                If you need a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as you want, the text will not appear divided and does not contain language errors, the Arabic text generator
                Useful for web designers in particular, where the client often needs to see a real picture of the site\'s design
            </p>
            <p>
                Hence, the designer must put temporary texts on the design to show the client the complete form. The role of the Arabic text generator is to save the designer the trouble of searching for text
                An alternative that has nothing to do with the topic that the design is talking about, so it appears inappropriate
            </p>
            <p>This text can be installed on any design without a problem. It will not look like copied, disorganized, unformatted, or even incomprehensible text. Because it is still an alternative and temporary text</p>
        ';

        $data = array('wan-san-yip-ID-4.png', 'redd-PTRzqc_h-3.png', 'news.png', 'wan-san-yip-ID-4.png');

        $stories01['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories01['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories01['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories01['background'] = 'asset-7.png';
        $stories01['images'] = json_encode($data);
        $stories01['service_id'] = 1;

        SuccessStories::create($stories01);


        $stories02['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories02['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories02['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories02['background'] = 'Group 450.png';
        $stories02['images'] = json_encode($data);
        $stories02['service_id'] = 1;

        SuccessStories::create($stories02);


        $stories03['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories03['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories03['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories03['background'] = 'md-duran-rE-2.png';
        $stories03['images'] = json_encode($data);
        $stories03['service_id'] = 2;

        SuccessStories::create($stories03);


        $stories04['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories04['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories04['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories04['background'] = 'md-duran-rE-2.png';
        $stories04['images'] = json_encode($data);
        $stories04['service_id'] = 2;

        SuccessStories::create($stories04);


        $stories05['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories05['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories05['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories05['background'] = 'Group 450.png';
        $stories05['images'] = json_encode($data);
        $stories05['service_id'] = 3;

        SuccessStories::create($stories05);


        $stories06['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories06['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories06['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories06['background'] = 'md-duran-rE-2.png';
        $stories06['images'] = json_encode($data);
        $stories06['service_id'] = 3;

        SuccessStories::create($stories06);


        $stories07['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories07['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories07['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories07['background'] = 'md-duran-rE-2.png';
        $stories07['images'] = json_encode($data);
        $stories07['service_id'] = 4;

        SuccessStories::create($stories07);


        $stories08['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories08['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories08['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories08['background'] = 'md-duran-rE-2.png';
        $stories08['images'] = json_encode($data);
        $stories08['service_id'] = 4;

        SuccessStories::create($stories08);


        $stories09['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories09['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories09['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories09['background'] = 'md-duran-rE-2.png';
        $stories09['images'] = json_encode($data);
        $stories09['service_id'] = 5;

        SuccessStories::create($stories09);


        $stories10['title'] = [
            'ar'            => 'مشروع تحديث أنظمة البنك ',
            'en'            => 'Bank systems modernization project'
        ];
        $stories10['description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories10['onther_description'] = [
            'ar'            => $info_ar,
            'en'            => $info_en
        ];
        $stories10['background'] = 'md-duran-rE-2.png';
        $stories10['images'] = json_encode($data);
        $stories10['service_id'] = 5;

        SuccessStories::create($stories10);
    }
}
